name: Build Benchmark DLLs

on:
  push:
    branches: [ "feature/*" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-benchmarks:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Legacy, Snapshot, Final]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Inject Benchmark Macros
      shell: pwsh
      run: |
        if ("${{ matrix.build_type }}" -eq "Legacy") {
            (Get-Content OptiScaler/upscalers/fsr31/FSR31Feature_Dx12.cpp) -replace '^#include <pch\.h>', "#include <pch.h>`r`n#define FRAMEBRIDGE_RUNTIME_CONFIG_BENCHMARK`r`n#define FRAMEBRIDGE_BENCHMARK_PATH `"Legacy`"" | Set-Content OptiScaler/upscalers/fsr31/FSR31Feature_Dx12.cpp
        }
        elseif ("${{ matrix.build_type }}" -eq "Snapshot") {
            (Get-Content OptiScaler/upscalers/fsr31/FSR31Feature_Dx12.cpp) -replace '^#include <pch\.h>', "#include <pch.h>`r`n#define FRAMEBRIDGE_BENCHMARK_PATH `"Snapshot`"" | Set-Content OptiScaler/upscalers/fsr31/FSR31Feature_Dx12.cpp
        }
        
        # Timer macro injection
        (Get-Content OptiScaler/upscalers/fsr31/FSR31Feature_Dx12.cpp) -replace '^#include <pch\.h>', "#include <pch.h>`r`n#define FRAMEBRIDGE_ENABLE_EVALUATE_TIMER" | Set-Content OptiScaler/upscalers/fsr31/FSR31Feature_Dx12.cpp

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build with MSBuild
      run: msbuild /m /p:Configuration=Release . /verbosity:minimal

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with: 
        name: OptiScaler_${{ matrix.build_type }}_DLL
        path: x64\Release\a\OptiScaler.dll
        compression-level: 9
        if-no-files-found: error
